version: '3.7'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"